spring:
  port: 8080
  profiles:
    active: ${APP_PROFILE:test}
  jpa:
    open-in-view: false

jwt:
  secret: ${JWT_SECRET:my-secret-strong}
  duration: ${JWT_DURATION:86400}

security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:dscatalog}
      client-secret: ${CLIENT_SECRET:dscatalog123}

cors:
  origins: ${CORS_ORIGINS:https://devsuperior.com.br,http://localhost:8080}